apiVersion:  apps/v1
kind: Deployment
metadata:
  name: deepfence-internalRouter
  namespace: {{ .Release.Namespace }}
  labels:
    app: deepfence-console
    name: deepfence-internal-router
    {{- include "deepfence-console.labels" . | nindent 4 }}
spec:
  {{- if not .Values.internalRouter.autoscaling.enabled }}
  replicas: {{ .Values.internalRouter.replicaCount }}
  {{- end }}  
  selector:
    matchLabels:
      name: deepfence-internal-router
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-internal-router
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
      - image: "{{ .Values.internalRouter.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.router.image.pullPolicy }}
        name: deepfence-internal-router
        env:
          - name: ENABLE_AUTH
            value: "false"
        volumeMounts:
        {{- if .Values.tls.pemfile }}
          - name: deepfence-cert-volume
            mountPath: /usr/local/etc/haproxy/deepfence.pem
            subPath: deepfence.pem
        {{- end }}
        {{- if and .Values.tls.certFile .Values.tls.keyFile }}
        - name: deepfence-ui-ssl-cert-file
          mountPath: /etc/deepfence/certs/deepfence.crt
          subPath: deepfence.crt
          readOnly: true
        - name: deepfence-ui-ssl-key-file
          mountPath: /etc/deepfence/certs/deepfence.key
          subPath: deepfence.key
          readOnly: true
        {{- end }}
        ports:
        - containerPort: 443
        resources:
          requests:
            memory: 100Mi
            cpu: {{ .Values.defaultResourceLimits.requests.cpu }}
{{- if eq "true" .Values.setDefaultResourceLimits }}
          limits:
            cpu: {{ .Values.defaultResourceLimits.limits.cpu }}
            memory: {{ .Values.defaultResourceLimits.limits.memory }}
{{- end }}
    {{- with .Values.internalRouter.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.topologyNodeAffinityHostName }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - "{{ .Values.topologyNodeAffinityHostName }}"
{{- end }}
    {{- with .Values.internalRouter.tolerations }}
    tolerations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.tls.pemfile }}
        - name: deepfence-cert-volume
          configMap:
            name: deepfence-cert
      {{- end }}
      {{- if and .Values.tls.certFile .Values.tls.keyFile }}
      - name: deepfence-ui-ssl-cert-file
        configMap:
          name: deepfence-ui-ssl-cert
      - name: deepfence-ui-ssl-key-file
        configMap:
          name: deepfence-ui-ssl-cert
      {{- end }}
